namespace LinkittyDo.Api.Models;

/// <summary>
/// Represents a game phrase stored in the phrase manager
/// </summary>
public class GamePhrase
{
    /// <summary>
    /// Unique identifier for this phrase (format: PHR-{timestamp}-{random})
    /// </summary>
    public string UniqueId { get; set; } = string.Empty;
    
    /// <summary>
    /// The full phrase text
    /// </summary>
    public string Text { get; set; } = string.Empty;
    
    /// <summary>
    /// Number of words in the phrase
    /// </summary>
    public int WordCount { get; set; }
    
    /// <summary>
    /// Whether this phrase was generated by an LLM
    /// </summary>
    public bool GeneratedByLlm { get; set; }
    
    /// <summary>
    /// When this phrase was added to the manager
    /// </summary>
    public DateTime CreatedAt { get; set; }
    
    /// <summary>
    /// Generates a unique phrase ID following the format: PHR-{timestamp}-{random}
    /// </summary>
    public static string GenerateUniqueId()
    {
        var timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        var random = Guid.NewGuid().ToString("N").Substring(0, 6).ToUpperInvariant();
        return $"PHR-{timestamp}-{random}";
    }
}
