// <auto-generated />
using System;
using LinkittyDo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkittyDo.Api.Migrations
{
    [DbContext(typeof(LinkittyDoDbContext))]
    partial class LinkittyDoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LinkittyDo.Api.Models.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.ClueEffectiveness", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AvgGuessesAfterClue")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TargetWord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TimesLedToCorrectGuess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TimesShown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UrlDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TargetWord", "SearchTerm", "UrlDomain")
                        .IsUnique();

                    b.ToTable("ClueEffectiveness");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.GameEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "SequenceNumber");

                    b.ToTable("GameEvents");

                    b.HasDiscriminator().HasValue("GameEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.GamePhrase", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("GeneratedByLlm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("UniqueId");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("GamePhrases");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.GameRecord", b =>
                {
                    b.Property<string>("GameId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsSimulated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("PhraseId")
                        .HasColumnType("int");

                    b.Property<string>("PhraseText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("InProgress");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("GameId");

                    b.HasIndex("UserId", "PlayedAt");

                    b.ToTable("GameRecords");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.GameSessionRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhraseUniqueId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("SessionId");

                    b.HasIndex("LastActivityAt");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.PhraseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PhraseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Common idiomatic expressions",
                            IsActive = true,
                            Name = "Idioms"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Traditional sayings and proverbs",
                            IsActive = true,
                            Name = "Proverbs"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Famous quotes and expressions",
                            IsActive = true,
                            Name = "Quotes"
                        },
                        new
                        {
                            Id = 4,
                            Description = "References from movies, TV, and music",
                            IsActive = true,
                            Name = "Pop Culture"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Scientific terms and concepts",
                            IsActive = true,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Literary references and phrases",
                            IsActive = true,
                            Name = "Literature"
                        });
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.PhraseCategoryAssignment", b =>
                {
                    b.Property<string>("PhraseUniqueId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("PhraseUniqueId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PhraseCategoryAssignments");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.PhrasePlayStats", b =>
                {
                    b.Property<string>("PhraseUniqueId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("AvgCluesToSolve")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("AvgTimeToSolveSeconds")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("CalibratedDifficulty")
                        .HasColumnType("int");

                    b.Property<decimal>("GiveUpRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SolveRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TimesGaveUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TimesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TimesSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("PhraseUniqueId");

                    b.ToTable("PhrasePlayStats");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.PhraseReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhraseUniqueId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PhraseUniqueId");

                    b.HasIndex("Status");

                    b.ToTable("PhraseReviews");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.PlayerStats", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("AvgCluesPerGame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("AvgGuessesPerGame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("AvgScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("BestScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("BestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GamesGaveUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GamesSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Player"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.SimulationProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgActionDelaySeconds")
                        .HasColumnType("int");

                    b.Property<decimal>("ClueProbability")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("CorrectGuessProbability")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("GiveUpProbability")
                        .HasColumnType("decimal(3,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PreferredDifficulty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SimulationProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgActionDelaySeconds = 5,
                            ClueProbability = 0.8m,
                            CorrectGuessProbability = 0.3m,
                            CreatedAt = new DateTime(2026, 4, 10, 11, 5, 23, 117, DateTimeKind.Utc).AddTicks(7648),
                            Description = "Simulates a beginner player",
                            GiveUpProbability = 0.2m,
                            IsActive = true,
                            Name = "Beginner",
                            PreferredDifficulty = 20
                        },
                        new
                        {
                            Id = 2,
                            AvgActionDelaySeconds = 5,
                            ClueProbability = 0.5m,
                            CorrectGuessProbability = 0.6m,
                            CreatedAt = new DateTime(2026, 4, 10, 11, 5, 23, 117, DateTimeKind.Utc).AddTicks(7652),
                            Description = "Simulates an average player",
                            GiveUpProbability = 0.1m,
                            IsActive = true,
                            Name = "Average",
                            PreferredDifficulty = 50
                        },
                        new
                        {
                            Id = 3,
                            AvgActionDelaySeconds = 5,
                            ClueProbability = 0.2m,
                            CorrectGuessProbability = 0.9m,
                            CreatedAt = new DateTime(2026, 4, 10, 11, 5, 23, 117, DateTimeKind.Utc).AddTicks(7654),
                            Description = "Simulates an expert player",
                            GiveUpProbability = 0.02m,
                            IsActive = true,
                            Name = "Expert",
                            PreferredDifficulty = 80
                        });
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.SiteConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Key");

                    b.ToTable("SiteConfigs");

                    b.HasData(
                        new
                        {
                            Key = "MaxSessionTtlHours",
                            Description = "Maximum session time-to-live in hours",
                            UpdatedAt = new DateTime(2026, 4, 10, 11, 5, 23, 116, DateTimeKind.Utc).AddTicks(8979),
                            Value = "24",
                            ValueType = "int"
                        },
                        new
                        {
                            Key = "DefaultDifficulty",
                            Description = "Default difficulty for new games",
                            UpdatedAt = new DateTime(2026, 4, 10, 11, 5, 23, 116, DateTimeKind.Utc).AddTicks(8982),
                            Value = "10",
                            ValueType = "int"
                        },
                        new
                        {
                            Key = "ClueRetryLimit",
                            Description = "Maximum clue retries per word",
                            UpdatedAt = new DateTime(2026, 4, 10, 11, 5, 23, 116, DateTimeKind.Utc).AddTicks(8983),
                            Value = "5",
                            ValueType = "int"
                        },
                        new
                        {
                            Key = "MaintenanceMode",
                            Description = "Enable maintenance mode",
                            UpdatedAt = new DateTime(2026, 4, 10, 11, 5, 23, 116, DateTimeKind.Utc).AddTicks(8983),
                            Value = "false",
                            ValueType = "bool"
                        });
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.User", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSimulated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("LifetimePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PreferredDifficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UniqueId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.ClueEvent", b =>
                {
                    b.HasBaseType("LinkittyDo.Api.Models.GameEvent");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("WordIndex")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("clue");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.GameEndEvent", b =>
                {
                    b.HasBaseType("LinkittyDo.Api.Models.GameEvent");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasDiscriminator().HasValue("gameend");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.GuessEvent", b =>
                {
                    b.HasBaseType("LinkittyDo.Api.Models.GameEvent");

                    b.Property<string>("GuessText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int");

                    b.Property<int>("WordIndex")
                        .HasColumnType("int");

                    b.ToTable("GameEvents", t =>
                        {
                            t.Property("WordIndex")
                                .HasColumnName("GuessEvent_WordIndex");
                        });

                    b.HasDiscriminator().HasValue("guess");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.PhraseCategoryAssignment", b =>
                {
                    b.HasOne("LinkittyDo.Api.Models.PhraseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkittyDo.Api.Models.GamePhrase", "Phrase")
                        .WithMany()
                        .HasForeignKey("PhraseUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Phrase");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.PhraseReview", b =>
                {
                    b.HasOne("LinkittyDo.Api.Models.GamePhrase", "Phrase")
                        .WithMany()
                        .HasForeignKey("PhraseUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");
                });

            modelBuilder.Entity("LinkittyDo.Api.Models.UserRole", b =>
                {
                    b.HasOne("LinkittyDo.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkittyDo.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
